<#
.SYNOPSIS
  registry.json 에서 파생 산출물을 생성한다(현재: project-manager.md 의 라우팅 블록).

.DESCRIPTION
  이 저장소는 에이전트 전체 명단을 네 곳에 손으로 유지해 왔다 — README 표, AGENTS 표,
  CLAUDE 표, 그리고 project-manager.md 의 라우팅 참조. 손으로 유지하는 명단은 반드시 썩는다:
  1.93 시점에 PM 라우팅은 73종 중 16종(22%)을 모르고 있었고, 그래서 조율자가 신설
  에이전트로 일을 보내지 못했다.

  이 스크립트는 그중 **순수하게 파생 가능한 것**(PM 라우팅 블록)을 생성한다.
  README·AGENTS 표는 사람이 쓴 뉘앙스가 많아 생성하지 않고, lint-agents.ps1 이
  "에이전트마다 행이 있는가"만 검증한다(생성 대신 검증 — 손으로 쓴 설명을 기계가 뭉개지 않게).

.PARAMETER Check
  파일을 고치지 않고 드리프트만 확인한다. 어긋나면 종료 코드 1.
  (lint-agents.ps1 과 CI·사전 훅에서 이 모드로 부른다)

.EXAMPLE
  .\build-registry.ps1          # 생성해서 반영
  .\build-registry.ps1 -Check   # 드리프트만 확인
#>
[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
if (-not $root) { $root = (Get-Location).Path }

function Read-Text { param([string]$f) [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8) }

$registryPath = Join-Path $root 'registry.json'
$pmPath       = Join-Path $root 'project-manager.md'

if (-not (Test-Path $registryPath)) { Write-Host "registry.json 이 없다." -ForegroundColor Red; exit 1 }
$reg = Read-Text $registryPath | ConvertFrom-Json

# ------------------------------------------------ registry ↔ 실제 파일 대조 --
$fileNames = @{}
Get-ChildItem -Path $root -Filter *.md -File | ForEach-Object {
    $t = Read-Text $_.FullName
    if ($t -match '(?m)^name:\s*(\S+)') { $fileNames[$Matches[1]] = $true }
}

$regNames = @{}
foreach ($p in $reg.agents.PSObject.Properties) { $regNames[$p.Name] = $p.Value }
foreach ($e in $reg.entryPoints) { $regNames[$e] = $null }

$missing = @($fileNames.Keys | Where-Object { -not $regNames.ContainsKey($_) } | Sort-Object)
$ghost   = @($regNames.Keys  | Where-Object { -not $fileNames.ContainsKey($_) } | Sort-Object)

$problem = $false
if ($missing.Count -gt 0) {
    Write-Host "registry.json 에 없는 에이전트 $($missing.Count)종:" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    $problem = $true
}
if ($ghost.Count -gt 0) {
    Write-Host "registry.json 에만 있고 파일이 없는 이름 $($ghost.Count)개:" -ForegroundColor Red
    $ghost | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    $problem = $true
}
if ($problem) {
    Write-Host "registry.json 을 실제 파일 집합에 맞춘 뒤 다시 실행할 것." -ForegroundColor Red
    exit 1
}

# ------------------------------------------------------- 라우팅 블록 생성 --
$lines = New-Object System.Collections.ArrayList
foreach ($group in $reg.groupOrder) {
    $items = @()
    foreach ($p in $reg.agents.PSObject.Properties) {
        if ($p.Value.group -eq $group) {
            $note = $p.Value.note
            if ([string]::IsNullOrWhiteSpace($note)) { $items += $p.Name }
            else { $items += "$note $($p.Name)" }
        }
    }
    if ($items.Count -eq 0) { continue }
    [void]$lines.Add("- **$group**: " + ($items -join ' · '))
}

$begin = '<!-- ROUTING:BEGIN (generated by build-registry.ps1 — do not edit by hand) -->'
$end   = '<!-- ROUTING:END -->'
$block = $begin + "`n" + ($lines -join "`n") + "`n" + $end

$pm = Read-Text $pmPath
$pattern = [regex]::Escape($begin) + '[\s\S]*?' + [regex]::Escape($end)
if ($pm -notmatch $pattern) {
    Write-Host "project-manager.md 에서 ROUTING 마커를 찾지 못했다." -ForegroundColor Red
    exit 1
}
$updated = [regex]::Replace($pm, $pattern, { param($m) $block })

$agentCount = @($reg.agents | Get-Member -MemberType NoteProperty).Count
if ($updated -eq $pm) {
    Write-Host "라우팅 블록 최신 — 에이전트 $($agentCount)종 / 묶음 $($lines.Count)개" -ForegroundColor Green
    exit 0
}

if ($Check) {
    Write-Host "라우팅 블록이 registry.json 과 어긋난다. '.\build-registry.ps1' 로 재생성할 것." -ForegroundColor Red
    exit 1
}

# BOM 없이 저장한다 — 정의 .md 는 BOM 없는 UTF-8 이 저장소 관행이다
# (.ps1 만 PowerShell 5.1 때문에 BOM 이 필요하다)
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($pmPath, $updated, $enc)
Write-Host "project-manager.md 라우팅 블록 갱신 — 에이전트 $($agentCount)종 / 묶음 $($lines.Count)개" -ForegroundColor Cyan
Write-Host "PM 의 version/updated 를 올리고 CHANGELOG 에 남긴 뒤 sync.ps1 을 실행할 것." -ForegroundColor Yellow
exit 0
